name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-12.04
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Build
      run: cargo build --release -v
    - uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: target/release/*.so

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Build
      run: cargo build --release -v
    - uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: target/release/*.dll

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build
        run: cargo build --release -v
      - uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: target/release/*.dylib
